# Generated by Django 6.0.8 on 2026-08-25 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=40, unique=True)),
                ('street', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRepresentative',
            fields=[
                ('service_rep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_rep_name', models.CharField(max_length=40, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('start_date', models.DateTimeField()),
                ('specialization', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticket_creation_timestamp', models.DateTimeField(auto_created=True)),
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=80)),
                ('model_number', models.IntegerField()),
                ('scope_of_work', models.TextField(max_length=1000)),
                ('service_rep_notes', models.TextField(max_length=1000)),
                ('repair_completion', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tickets.customer')),
                ('service_rep_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tickets.servicerepresentative')),
            ],
        ),
        migrations.CreateModel(
            name='HistTicketRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_assigned_timestamp', models.DateTimeField()),
                ('ticket_completion_timestamp', models.DateTimeField()),
                ('service_rep_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tickets.servicerepresentative')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.supportticket')),
            ],
        ),
    ]
