# Generated by Django 6.0.8 on 2026-08-28 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histticketrecord',
            old_name='service_rep_id',
            new_name='service_rep',
        ),
        migrations.RenameField(
            model_name='histticketrecord',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='histticketrecord',
            name='ticket_completion_timestamp',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='repair_completion',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='service_rep_id',
        ),
        migrations.AddField(
            model_name='histticketrecord',
            name='ticket_unassigned_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='repair_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='service_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tickets.servicerepresentative'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ticket_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='servicerepresentative',
            name='service_rep_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='servicerepresentative',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='model_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_creation_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
