# Generated by Django 6.0.8 on 2026-09-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_service_rep_id_histticketrecord_service_rep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='service_rep_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
